[package]
name = "roml-highs"
version = "0.1.0"
edition = "2021"
description = "HiGHS solver backend for roml"

[dependencies]
highs-sys = { version = "1.15", default-features = false }
log = "0.4"
roml = { path = ".." }

[features]
default = ["bundled"]
bundled = ["highs-sys/build", "highs-sys/highs_release"]
system = ["highs-sys/discover"]
