[package]
name = "roml-highs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "HiGHS solver backend for roml"
include = [
    "Cargo.toml",
    "build.rs",
    "src/**",
    "tests/**",
    "examples/**",
    "benches/**",
]

[dependencies]
highs-sys = { version = "1.15", default-features = false }
log = "0.4"
roml = { version = "0.1.0", path = ".." }

[features]
default = ["bundled"]
bundled = ["highs-sys/build", "highs-sys/highs_release"]
system = ["highs-sys/discover"]

[[bench]]
name = "iis"
harness = false
