[package]
name = "roml-highs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "HiGHS solver backend for roml"
include = [
    "Cargo.toml",
    "build.rs",
    "src/**",
    "tests/**",
    "examples/**",
]

[dependencies]
highs-sys = "1.15"
log = "0.4"
roml = { version = "0.1.0", path = ".." }

[features]
default = ["bundled"]
bundled = []
system = []
