//! Solver-agnostic MIP callback types for cutting planes and lazy constraints.
//!
//! Solver adapters translate between their native callback mechanisms and
//! the types defined here. This allows problem-specific cutting plane
//! generation (e.g., subtour elimination in TSP) to work across multiple
//! solver backends (HiGHS, MOSEK, Xpress).

use std::collections::HashMap;

use crate::VarId;

/// Information about the current MIP state passed to a callback handler.
#[derive(Clone, Debug)]
pub struct CallbackData {
    /// Variable values at the current node (LP relaxation or candidate solution).
    /// Keyed by roml `VarId`.
    pub var_values: HashMap<VarId, f64>,

    /// Current primal bound (best feasible solution objective found).
    pub primal_bound: f64,

    /// Current dual bound (best LP relaxation bound).
    pub dual_bound: f64,

    /// MIP gap as a fraction (may be `f64::INFINITY` if no primal bound yet).
    pub mip_gap: f64,
}

/// A linear cut (inequality) generated by a callback handler.
#[derive(Clone, Debug)]
pub struct CallbackCut {
    /// Variable-coefficient pairs: the LHS of this cut.
    pub terms: Vec<(VarId, f64)>,

    /// Lower bound of the cut (use `f64::NEG_INFINITY` for ≤-only cuts).
    pub lower: f64,

    /// Upper bound of the cut (use `f64::INFINITY` for ≥-only cuts).
    pub upper: f64,
}

/// Action the callback handler requests from the solver.
#[derive(Clone, Debug)]
pub enum CallbackAction {
    /// Accept the current candidate solution (all lazy constraints satisfied).
    Accept,

    /// Add these cuts to the formulation and re-solve the current node.
    AddCuts(Vec<CallbackCut>),
}

/// Trait for callback handlers invoked during MIP branch-and-cut.
///
/// Implement this trait to add problem-specific cutting planes or
/// lazy constraints. The solver adapter invokes these methods from
/// within its native callback mechanism.
///
/// # Safety
///
/// The handler is called from within the solver's native callback,
/// typically on the main solver thread. It must not block for long
/// periods or attempt to call back into the solver. The handler must
/// be `Send` because it may be moved across threads during setup.
pub trait CallbackHandler: Send {
    /// Called when a candidate integer solution needs lazy constraint checking.
    ///
    /// The handler should inspect `data.var_values`, identify violated
    /// constraints, and return either `Accept` (no violations) or `AddCuts`
    /// with the violated constraints to add.
    fn on_candidate(&mut self, data: &CallbackData) -> CallbackAction;
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Mock handler that always accepts.
    struct AcceptHandler;
    impl CallbackHandler for AcceptHandler {
        fn on_candidate(&mut self, _data: &CallbackData) -> CallbackAction {
            CallbackAction::Accept
        }
    }

    /// Mock handler that always adds a dummy cut.
    struct CutHandler;
    impl CallbackHandler for CutHandler {
        fn on_candidate(&mut self, _data: &CallbackData) -> CallbackAction {
            CallbackAction::AddCuts(vec![
                CallbackCut {
                    terms: vec![],
                    lower: f64::NEG_INFINITY,
                    upper: 0.0,
                }
            ])
        }
    }

    #[test]
    fn callback_data_constructible() {
        let data = CallbackData {
            var_values: HashMap::new(),
            primal_bound: 100.0,
            dual_bound: 80.0,
            mip_gap: 0.2,
        };
        assert!(data.var_values.is_empty());
        assert_eq!(data.primal_bound, 100.0);
        assert_eq!(data.mip_gap, 0.2);
    }

    #[test]
    fn accept_handler_returns_accept() {
        let mut h = AcceptHandler;
        let data = CallbackData {
            var_values: HashMap::new(),
            primal_bound: 0.0,
            dual_bound: 0.0,
            mip_gap: 0.0,
        };
        match h.on_candidate(&data) {
            CallbackAction::Accept => {} // expected
            _ => panic!("expected Accept"),
        }
    }

    #[test]
    fn cut_handler_returns_cuts() {
        let mut h = CutHandler;
        let data = CallbackData {
            var_values: HashMap::new(),
            primal_bound: 0.0,
            dual_bound: 0.0,
            mip_gap: 0.0,
        };
        match h.on_candidate(&data) {
            CallbackAction::AddCuts(cuts) => {
                assert_eq!(cuts.len(), 1);
                assert_eq!(cuts[0].upper, 0.0);
            }
            _ => panic!("expected AddCuts"),
        }
    }

    #[test]
    fn cut_round_trip() {
        let cut = CallbackCut {
            terms: vec![],
            lower: 5.0,
            upper: 10.0,
        };
        assert!(cut.terms.is_empty());
        assert!((cut.lower - 5.0).abs() < 1e-9);
        assert!((cut.upper - 10.0).abs() < 1e-9);
    }
}
