//! LP infeasibility analysis contracts.
//!
//! The first Phase 29 slice freezes the public vocabulary and the typed
//! tri-state feasibility rule. Execution machinery is added in later slices.

use std::collections::HashMap;
use std::fmt;

use crate::compiler::backend_ir::{
    BackendSnapshot, CompilationId, CompiledConstraintId, CompiledEntityRef, CompiledVariableId,
};
use crate::compiler::origin::{EntityOrigin, GeneratedRole};
use crate::compiler::report::BackendIdentity;
use crate::construct::Construct;
use crate::identity::{ModelInstanceId, ModelLineageId};
use crate::model::{Constraint, Model, Variable};
use crate::revision::ModelRevision;
use crate::solver::backend::{BackendError, TerminationStatus};
use crate::solver::overlay::SolveOverlay;

/// Selects the provider strategy for LP infeasibility analysis.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InfeasibilityMode {
    /// Prefer a qualified native seed and reduce it semantically, with a
    /// portable fallback when native analysis is unavailable.
    Auto,
    /// Use only the solver-agnostic ROML reducer.
    RomlPortable,
    /// Require a qualified native provider and never fall back.
    NativeOnly,
    /// Require native seed acquisition, followed by ROML semantic reduction.
    NativeThenRoml,
}

/// Selects which LP model scope is analyzed.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InfeasibilityScope {
    /// Analyze the original continuous LP model.
    OriginalLp,
    /// Analyze an explicitly requested LP relaxation of a MIP model.
    LpRelaxation,
}

/// Selects how semantic restrictions are grouped into candidate atoms.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ConflictGrouping {
    /// Use semantic ROML entities as atoms, including equality restrictions and
    /// generated constructs. This is the default user-facing grouping.
    Semantic,
    /// Keep each independently toggleable semantic restriction separate.
    Individual,
    /// Keep restrictions generated by one semantic construct together.
    ByConstruct,
}

/// Selects the initial conflict seed strategy.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SeedPolicy {
    /// Use the cheapest qualified seed, then fall back through the provider
    /// chain defined by the analysis mode.
    Adaptive,
    /// Start with every semantic restriction in the requested universe.
    FullUniverse,
}

/// Selects the semantic deletion strategy.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReductionPolicy {
    /// Use adaptive chunk deletion followed by exact single-atom polishing.
    Adaptive,
    /// Use exact single-atom deletion only.
    SingleAtom,
}

/// Bounds the work performed by one infeasibility analysis.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct AnalysisBudget {
    /// Maximum number of feasibility-oracle calls, if bounded.
    pub max_oracle_calls: Option<u64>,
    /// Maximum number of reducer iterations, if bounded.
    pub max_iterations: Option<u64>,
    /// Maximum wall-clock time for one backend feasibility check.
    pub time_limit_ms: Option<u64>,
}

/// Controls numerical tolerances used by the feasibility oracle and verifier.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct AnalysisNumericalPolicy {
    /// Feasibility tolerance used by qualified oracle checks.
    pub feasibility_tolerance: f64,
}

impl Default for AnalysisNumericalPolicy {
    fn default() -> Self {
        Self {
            feasibility_tolerance: 1e-7,
        }
    }
}

/// Complete request for one LP infeasibility analysis.
#[derive(Clone, Debug, PartialEq)]
pub struct InfeasibilityPlan {
    /// Provider strategy.
    pub mode: InfeasibilityMode,
    /// Requested LP scope.
    pub scope: InfeasibilityScope,
    /// Semantic atom grouping.
    pub grouping: ConflictGrouping,
    /// Initial seed policy.
    pub seed_policy: SeedPolicy,
    /// Reduction policy.
    pub reduction: ReductionPolicy,
    /// Work budget.
    pub budget: AnalysisBudget,
    /// Numerical policy.
    pub numerical_policy: AnalysisNumericalPolicy,
    /// Optional solve-scoped restrictions to include in the isolated analysis.
    pub overlay: Option<SolveOverlay>,
}

impl InfeasibilityPlan {
    /// Build the default portable analysis plan for the original LP.
    pub fn portable_lp() -> Self {
        Self {
            mode: InfeasibilityMode::RomlPortable,
            scope: InfeasibilityScope::OriginalLp,
            grouping: ConflictGrouping::Semantic,
            seed_policy: SeedPolicy::Adaptive,
            reduction: ReductionPolicy::Adaptive,
            budget: AnalysisBudget::default(),
            numerical_policy: AnalysisNumericalPolicy::default(),
            overlay: None,
        }
    }
}

/// Evidence that an oracle proved the selected restrictions feasible.
#[derive(Clone, Debug, PartialEq)]
pub struct FeasibilityEvidence {
    /// Backend termination status supporting the proof.
    pub termination: TerminationStatus,
}

/// Evidence that an oracle proved the selected restrictions infeasible.
#[derive(Clone, Debug, PartialEq)]
pub struct InfeasibilityEvidence {
    /// Backend termination status supporting the proof.
    pub termination: TerminationStatus,
}

/// Reason an oracle could not prove either feasibility result.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UnknownReason {
    /// The backend reported an infeasible-or-unbounded ambiguity.
    Ambiguous,
    /// The backend reported unboundedness without a feasibility proof under
    /// the analysis policy.
    Unbounded,
    /// A legacy aggregate limit reason.
    #[deprecated(note = "use the specific limit reason variants")]
    Limit,
    /// A backend wall-clock limit prevented a proof.
    TimeLimit,
    /// A backend simplex/iteration limit prevented a proof.
    IterationLimit,
    /// A backend MIP node limit prevented a proof.
    NodeLimit,
    /// The backend was interrupted.
    Interrupted,
    /// Numerical behavior prevented a reliable proof.
    Numerical,
    /// The backend returned an operational error.
    BackendError,
    /// The backend returned an unclassified status.
    Unclassified,
}

/// Which side of a two-sided semantic restriction is represented.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BoundSide {
    /// Lower side.
    Lower,
    /// Upper side.
    Upper,
}

/// Semantic class of one conflict atom.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ConflictAtomKind {
    /// One side of a user constraint.
    ConstraintSide(BoundSide),
    /// Both sides of one exact user constraint.
    ConstraintEquality,
    /// One variable bound side.
    VariableBound(BoundSide),
    /// Both sides of one exact variable bound.
    VariableEquality,
    /// A persistent fixing contribution.
    PersistentFixing,
    /// A solve-scoped lock contribution.
    SolveLock,
    /// A temporary fixing contribution.
    TemporaryFixing,
    /// A grouped generated semantic construct.
    GroupedConstruct,
    /// A solve-scoped overlay contribution.
    SolveOverlay,
    /// Reserved function-in-set semantic member for later nonlinear work.
    FunctionInSet,
}

/// Original semantic origin of one restriction atom.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum ConflictOrigin {
    /// A user constraint side.
    ConstraintSide {
        /// User constraint.
        constraint: Constraint,
        /// Side represented.
        side: BoundSide,
    },
    /// An exact user constraint represented as one semantic member.
    ConstraintEquality {
        /// User constraint.
        constraint: Constraint,
    },
    /// A user variable bound side.
    VariableBound {
        /// User variable.
        variable: Variable,
        /// Side represented.
        side: BoundSide,
    },
    /// An exact user variable bound represented as one semantic member.
    VariableEquality {
        /// User variable.
        variable: Variable,
    },
    /// A persistent fixing on a variable.
    PersistentFixing {
        /// User variable.
        variable: Variable,
    },
    /// A solve lock on a variable.
    SolveLock {
        /// User variable.
        variable: Variable,
    },
    /// A temporary fixing on a variable.
    TemporaryFixing {
        /// User variable.
        variable: Variable,
    },
    /// A generated restriction grouped under one semantic construct.
    GroupedConstruct {
        /// Semantic construct.
        construct: Construct,
        /// Generated role.
        role: GeneratedRole,
    },
    /// A solve-scoped overlay contribution.
    SolveOverlay {
        /// Overlay identity.
        overlay: crate::compiler::origin::OverlayId,
        /// Generated overlay role.
        role: GeneratedRole,
    },
    /// A future function-in-set member.
    FunctionInSet {
        /// Function-in-set origin.
        origin: EntityOrigin,
    },
}

/// Immutable historical values retained for one conflict member.
#[derive(Clone, Debug, PartialEq)]
pub struct ConflictMemberSnapshot {
    /// Semantic origin.
    pub origin: ConflictOrigin,
    /// Optional source name.
    pub name: Option<String>,
    /// Bound value represented by this member, when applicable.
    pub value: Option<f64>,
}

/// Action used to toggle one semantic restriction.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RestrictionToggleAction {
    /// Disable the atom from the isolated analysis session.
    Disable,
    /// Restore the atom and its lower bound contribution layer.
    Restore,
}

/// Exact toggle operation for one semantic atom.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RestrictionTogglePlan {
    /// Atom affected by the operation.
    pub atom_id: ConflictAtomId,
    /// Operation to apply.
    pub action: RestrictionToggleAction,
}

/// The only outcomes an isolated feasibility oracle may return.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq)]
pub enum FeasibilityOutcome {
    /// Feasibility was proven.
    ProvenFeasible(FeasibilityEvidence),
    /// Infeasibility was proven.
    ProvenInfeasible(InfeasibilityEvidence),
    /// No proof was obtained.
    Unknown(UnknownReason),
}

/// Classify a backend termination without converting uncertainty to conflict.
pub fn classify_feasibility(status: TerminationStatus) -> FeasibilityOutcome {
    match status {
        TerminationStatus::Optimal | TerminationStatus::Feasible => {
            FeasibilityOutcome::ProvenFeasible(FeasibilityEvidence {
                termination: status,
            })
        }
        TerminationStatus::Infeasible => {
            FeasibilityOutcome::ProvenInfeasible(InfeasibilityEvidence {
                termination: status,
            })
        }
        TerminationStatus::InfeasibleOrUnbounded => {
            FeasibilityOutcome::Unknown(UnknownReason::Ambiguous)
        }
        TerminationStatus::Unbounded => FeasibilityOutcome::Unknown(UnknownReason::Unbounded),
        TerminationStatus::TimeLimit => FeasibilityOutcome::Unknown(UnknownReason::TimeLimit),
        TerminationStatus::IterationLimit => {
            FeasibilityOutcome::Unknown(UnknownReason::IterationLimit)
        }
        TerminationStatus::NodeLimit => FeasibilityOutcome::Unknown(UnknownReason::NodeLimit),
        TerminationStatus::Interrupted => FeasibilityOutcome::Unknown(UnknownReason::Interrupted),
        TerminationStatus::NumericalIssue => FeasibilityOutcome::Unknown(UnknownReason::Numerical),
        TerminationStatus::Error => FeasibilityOutcome::Unknown(UnknownReason::BackendError),
        TerminationStatus::Unknown => FeasibilityOutcome::Unknown(UnknownReason::Unclassified),
    }
}

/// Error returned by infeasibility analysis.
#[derive(Clone, Debug, PartialEq)]
pub enum InfeasibilityError {
    /// The requested provider or model scope is not qualified.
    Unsupported {
        /// Operation that was not qualified.
        operation: String,
    },
    /// A mapping or operation used a different exact compiled state.
    CompilationMismatch {
        /// Expected compiled state.
        expected: CompilationId,
        /// Supplied compiled state.
        actual: CompilationId,
    },
    /// A backend operation failed.
    Backend(BackendError),
    /// The compiled snapshot cannot produce a complete semantic universe.
    InvalidUniverse {
        /// Why the universe is invalid.
        reason: String,
    },
    /// A mandatory fresh verification contradicted the candidate result.
    VerificationFailure {
        /// Why the candidate could not be certified.
        reason: String,
    },
}

impl fmt::Display for InfeasibilityError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unsupported { operation } => {
                write!(f, "unsupported infeasibility operation: {operation}")
            }
            Self::CompilationMismatch { expected, actual } => {
                write!(
                    f,
                    "infeasibility compilation mismatch: expected {expected:?}, got {actual:?}"
                )
            }
            Self::Backend(error) => error.fmt(f),
            Self::InvalidUniverse { reason } => {
                write!(f, "invalid semantic conflict universe: {reason}")
            }
            Self::VerificationFailure { reason } => {
                write!(f, "infeasibility verification failed: {reason}")
            }
        }
    }
}

impl std::error::Error for InfeasibilityError {}

/// Guarantee attached to a conflict report.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConflictGuarantee {
    /// No conflict guarantee was established.
    None,
    /// Semantic irreducibility under the recorded universe, oracle, and
    /// numerical policy; never minimum cardinality.
    Irreducible,
    /// The backend reported a native conflict that was not semantically
    /// reduced to an irreducibility claim.
    NativeReported,
    /// A proven infeasible subsystem without enough proof for irreducibility.
    InfeasibleSubsystem,
}

/// Whether the analysis finished all required verification work.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AnalysisCompletion {
    /// Reduction and fresh verification completed.
    Complete,
    /// A legacy generic work-limit marker.
    #[deprecated(note = "use a specific completion limit variant")]
    Limit,
    /// The oracle-call budget stopped the analysis.
    OracleCallLimit,
    /// The reducer-iteration budget stopped the analysis.
    IterationLimit,
    /// A backend time limit prevented a proof.
    TimeLimit,
    /// A backend node limit prevented a proof.
    NodeLimit,
    /// The analysis was interrupted.
    Interrupted,
    /// Numerical behavior stopped the analysis.
    Numerical,
    /// A backend failure stopped the analysis.
    BackendFailure,
}

/// Result classification independent of completion and guarantee.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InfeasibilityOutcome {
    /// The requested model was proven feasible.
    NoConflict,
    /// A conflict was proven and reported.
    Conflict,
    /// Initial feasibility was unknown, so no no-conflict claim is made.
    NoConflictProof,
}

/// Strength of the feasibility oracle used by the report.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FeasibilityProofStrength {
    /// Every required check was proven.
    Proven,
    /// At least one check was limited or otherwise weaker.
    Limited,
    /// No proof was available.
    Unknown,
}

/// Provider record retained in report history.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AnalysisProviderRecord {
    /// Provider label.
    pub name: String,
}

/// Candidate-universe summary retained in report history.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CandidateUniverseSummary {
    /// Number of semantic candidate atoms.
    pub atom_count: usize,
    /// Grouping used to form candidate atoms.
    pub grouping: ConflictGrouping,
}

/// One semantic conflict member.
#[derive(Clone, Debug, PartialEq)]
pub struct ConflictMember {
    /// Stable semantic atom identifier.
    pub atom_id: ConflictAtomId,
    /// Historical semantic declaration snapshot.
    pub declaration: ConflictDeclarationSnapshot,
    /// Compiled references retained as technical evidence.
    pub compiled_evidence: Vec<CompiledRestrictionEvidence>,
}

/// Historical semantic declaration retained by a report.
pub type ConflictDeclarationSnapshot = ConflictMemberSnapshot;

/// One compiled restriction reference retained as report evidence.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CompiledRestrictionEvidence {
    /// Compiled restriction reference.
    pub reference: CompiledRestrictionRef,
    /// Native membership classification, if a native provider supplied it.
    pub native_membership: Option<NativeMembership>,
    /// Native bound-side classification, if supplied.
    pub native_bound: Option<NativeBoundStatus>,
}

/// Native membership evidence retained without promoting its guarantee.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NativeConflictEvidence {
    /// Provider label.
    pub provider: String,
    /// Full native row/column/bound-side evidence.
    pub evidence: Vec<NativeConflictMember>,
}

/// Counters collected during analysis.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct InfeasibilityStatistics {
    /// Number of oracle calls.
    pub oracle_calls: u64,
    /// Number of reducer iterations.
    pub iterations: u64,
    /// Number of fresh verifier checks.
    pub fresh_verification_checks: u64,
}

/// Warning retained in a report.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AnalysisWarning {
    /// Stable warning text.
    pub message: String,
}

/// Canonical structured infeasibility report.
#[derive(Clone, Debug, PartialEq)]
pub struct InfeasibilityReport {
    /// Model lineage.
    pub model_lineage: ModelLineageId,
    /// Exact model instance.
    pub model_instance: ModelInstanceId,
    /// Model revision analyzed.
    pub model_revision: ModelRevision,
    /// Exact compilation identity analyzed.
    pub compilation_id: CompilationId,
    /// Backend identity.
    pub backend: BackendIdentity,
    /// Provider chain.
    pub provider_chain: Vec<AnalysisProviderRecord>,
    /// Requested scope.
    pub scope: InfeasibilityScope,
    /// Candidate universe summary.
    pub candidate_universe: CandidateUniverseSummary,
    /// Outcome independent of completion.
    pub outcome: InfeasibilityOutcome,
    /// Completion state.
    pub completion: AnalysisCompletion,
    /// Conflict guarantee.
    pub guarantee: ConflictGuarantee,
    /// Oracle proof strength.
    pub oracle_strength: FeasibilityProofStrength,
    /// Numerical policy.
    pub numerical_policy: AnalysisNumericalPolicy,
    /// Semantic members.
    pub members: Vec<ConflictMember>,
    /// Optional native evidence.
    pub native_evidence: Option<NativeConflictEvidence>,
    /// Analysis statistics.
    pub statistics: InfeasibilityStatistics,
    /// Warnings.
    pub warnings: Vec<AnalysisWarning>,
}

/// Stable opaque identifier for a semantic conflict atom.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ConflictAtomId(pub u64);

/// Reference to one compiled restriction.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CompiledRestrictionRef {
    /// Lower side of a compiled row.
    ConstraintLower(CompiledConstraintId),
    /// Upper side of a compiled row.
    ConstraintUpper(CompiledConstraintId),
    /// Lower bound side of a compiled variable.
    VariableLower(CompiledVariableId),
    /// Upper bound side of a compiled variable.
    VariableUpper(CompiledVariableId),
    /// A compiled entity generated by a grouped semantic construct.
    Entity(CompiledEntityRef),
}

/// Semantic restriction universe used by a reducer and oracle.
#[derive(Clone, Debug, PartialEq)]
pub struct SemanticConflictUniverse {
    /// Exact compiled state this universe belongs to.
    pub compilation_id: CompilationId,
    /// Semantic atoms.
    pub atoms: Vec<SemanticRestrictionAtom>,
    /// Compiled restrictions represented by the atoms.
    pub compiled_restrictions: Vec<CompiledRestrictionRef>,
    /// Grouping policy used to form atoms.
    pub grouping: ConflictGrouping,
}

/// One semantically toggleable restriction atom.
#[derive(Clone, Debug, PartialEq)]
pub struct SemanticRestrictionAtom {
    /// Stable atom identifier.
    pub id: ConflictAtomId,
    /// Semantic class.
    pub kind: ConflictAtomKind,
    /// Original semantic origin.
    pub origin: ConflictOrigin,
    /// Compiled restrictions covered by this atom.
    pub compiled_restrictions: Vec<CompiledRestrictionRef>,
    /// Bound contribution for each compiled restriction. A grouped atom can
    /// cover several rows/columns with different values.
    pub restriction_values: Vec<(CompiledRestrictionRef, Option<f64>)>,
    /// Disable operation.
    pub disable: RestrictionTogglePlan,
    /// Restore operation.
    pub restore: RestrictionTogglePlan,
    /// Historical member data.
    pub snapshot: ConflictMemberSnapshot,
}

/// Selection of atoms to retain for one oracle check.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RestrictionSelection {
    /// Exact universe compilation identity.
    pub compilation_id: CompilationId,
    /// Selected atom identifiers.
    pub atom_ids: Vec<ConflictAtomId>,
}

impl RestrictionSelection {
    /// Select every atom in an exact universe.
    pub fn all(universe: &SemanticConflictUniverse) -> Self {
        Self {
            compilation_id: universe.compilation_id,
            atom_ids: universe.atoms.iter().map(|atom| atom.id).collect(),
        }
    }
}

/// Oracle budget for one feasibility check.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct OracleBudget {
    /// Optional backend time limit in milliseconds.
    pub time_limit_ms: Option<u64>,
    /// Feasibility tolerance to apply to the isolated backend session.
    pub feasibility_tolerance: Option<f64>,
}

/// Feasibility oracle used by the portable reducer.
pub trait FeasibilityOracle {
    /// Exact compiled state checked by this oracle.
    fn compilation_id(&self) -> CompilationId;

    /// Check one semantic restriction selection.
    fn check(
        &mut self,
        selection: &RestrictionSelection,
        budget: &OracleBudget,
    ) -> Result<FeasibilityOutcome, BackendError>;
}

impl<T: FeasibilityOracle + ?Sized> FeasibilityOracle for Box<T> {
    fn compilation_id(&self) -> CompilationId {
        (**self).compilation_id()
    }

    fn check(
        &mut self,
        selection: &RestrictionSelection,
        budget: &OracleBudget,
    ) -> Result<FeasibilityOutcome, BackendError> {
        (**self).check(selection, budget)
    }
}

/// Health of an isolated analysis session.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AnalysisSessionHealth {
    /// Candidate checks may proceed.
    Ready,
    /// A failed transition requires a fresh snapshot rebuild.
    RequiresRebuild,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
struct OracleCacheKey {
    compilation_id: CompilationId,
    universe_atoms: Vec<ConflictAtomId>,
    grouping: ConflictGrouping,
    atom_ids: Vec<ConflictAtomId>,
    tolerance_bits: u64,
}

/// Isolated, cache-aware orchestration around one feasibility oracle.
pub struct AnalysisSession<O> {
    oracle: O,
    compilation_id: CompilationId,
    atom_ids: Vec<ConflictAtomId>,
    grouping: ConflictGrouping,
    numerical_policy: AnalysisNumericalPolicy,
    cache: HashMap<OracleCacheKey, FeasibilityOutcome>,
    health: AnalysisSessionHealth,
    oracle_calls: u64,
}

impl<O: FeasibilityOracle> AnalysisSession<O> {
    /// Create an isolated analysis session for one exact universe.
    pub fn new(
        oracle: O,
        universe: &SemanticConflictUniverse,
        numerical_policy: AnalysisNumericalPolicy,
    ) -> Result<Self, InfeasibilityError> {
        if oracle.compilation_id() != universe.compilation_id {
            return Err(InfeasibilityError::CompilationMismatch {
                expected: universe.compilation_id,
                actual: oracle.compilation_id(),
            });
        }
        Ok(Self {
            compilation_id: universe.compilation_id,
            atom_ids: universe.atoms.iter().map(|atom| atom.id).collect(),
            grouping: universe.grouping,
            numerical_policy,
            cache: HashMap::new(),
            health: AnalysisSessionHealth::Ready,
            oracle,
            oracle_calls: 0,
        })
    }

    /// Current isolated-session health.
    pub fn health(&self) -> AnalysisSessionHealth {
        self.health
    }

    /// Number of backend oracle calls, excluding cache hits.
    pub fn oracle_calls(&self) -> u64 {
        self.oracle_calls
    }

    /// Mark the analysis session as requiring a fresh snapshot rebuild.
    pub fn mark_requires_rebuild(&mut self) {
        self.health = AnalysisSessionHealth::RequiresRebuild;
        self.cache.clear();
    }

    /// Check one selection, validating exact identity before consulting the
    /// isolated oracle and caching only exact-key results.
    pub fn check(
        &mut self,
        selection: &RestrictionSelection,
        budget: &OracleBudget,
    ) -> Result<FeasibilityOutcome, InfeasibilityError> {
        if self.health != AnalysisSessionHealth::Ready {
            return Err(InfeasibilityError::Unsupported {
                operation: "analysis session requires snapshot rebuild".to_string(),
            });
        }
        if selection.compilation_id != self.compilation_id {
            return Err(InfeasibilityError::CompilationMismatch {
                expected: self.compilation_id,
                actual: selection.compilation_id,
            });
        }
        if selection
            .atom_ids
            .iter()
            .any(|id| !self.atom_ids.contains(id))
        {
            return Err(InfeasibilityError::InvalidUniverse {
                reason: "selection contains an atom outside the exact universe".to_string(),
            });
        }
        let key = OracleCacheKey {
            compilation_id: self.compilation_id,
            universe_atoms: self.atom_ids.clone(),
            grouping: self.grouping,
            atom_ids: selection.atom_ids.clone(),
            tolerance_bits: self.numerical_policy.feasibility_tolerance.to_bits(),
        };
        if let Some(cached) = self.cache.get(&key) {
            return Ok(cached.clone());
        }
        let outcome = self.oracle.check(selection, budget).map_err(|error| {
            self.health = AnalysisSessionHealth::RequiresRebuild;
            self.cache.clear();
            InfeasibilityError::Backend(error)
        })?;
        self.oracle_calls += 1;
        self.cache.insert(key, outcome.clone());
        Ok(outcome)
    }

    /// Run a check against the backend without reusing a cached outcome.
    pub fn check_fresh(
        &mut self,
        selection: &RestrictionSelection,
        budget: &OracleBudget,
    ) -> Result<FeasibilityOutcome, InfeasibilityError> {
        self.cache.clear();
        self.check(selection, budget)
    }
}

/// Native conflict request passed through a qualified backend boundary.
#[derive(Clone, Debug, PartialEq)]
pub struct NativeConflictRequest {
    /// Exact compiled state requested.
    pub compilation_id: CompilationId,
    /// Exact compiled snapshot on which native analysis must run.
    pub snapshot: BackendSnapshot,
}

/// Native IIS membership classification for one compiled restriction.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NativeMembership {
    /// HiGHS says the restriction is not in the conflict.
    Excluded,
    /// HiGHS says the restriction may be in the conflict.
    Possible,
    /// HiGHS says the restriction is in the conflict.
    Member,
    /// The native status was not recognized by the audited adapter.
    Unknown(i32),
}

/// Native IIS bound classification retained as evidence.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NativeBoundStatus {
    /// No finite bound is represented.
    Free,
    /// Only the lower bound is represented.
    Lower,
    /// Only the upper bound is represented.
    Upper,
    /// Both bound sides are represented.
    Boxed,
    /// HiGHS dropped the restriction during its calculation.
    Dropped,
    /// The native value was not recognized by the audited adapter.
    Unknown(i32),
}

/// One native compiled membership record.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct NativeConflictMember {
    /// Compiled restriction represented by the native record.
    pub restriction: CompiledRestrictionRef,
    /// Native membership classification.
    pub membership: NativeMembership,
    /// Native bound classification, when provided.
    pub bound: Option<NativeBoundStatus>,
}

/// Native compiled-membership conflict result.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NativeConflict {
    /// Exact compiled state producing the evidence.
    pub compilation_id: CompilationId,
    /// Compiled restrictions reported by the provider.
    pub members: Vec<CompiledRestrictionRef>,
    /// Full row/column/bound-side native evidence.
    pub evidence: Vec<NativeConflictMember>,
}

/// Optional backend capability boundary for infeasibility analysis.
pub trait InfeasibilityOracleFactory {
    /// Oracle type created by this backend.
    type Oracle: FeasibilityOracle;

    /// Create an isolated oracle over one exact backend snapshot.
    fn spawn_infeasibility_oracle(
        &self,
        snapshot: &BackendSnapshot,
        universe: &SemanticConflictUniverse,
    ) -> Result<Self::Oracle, BackendError>;

    /// Request native compiled-membership evidence.
    fn native_conflict(
        &self,
        request: &NativeConflictRequest,
    ) -> Result<NativeConflict, BackendError>;
}

/// Compact structured-text view of a report.
pub struct TextInfeasibilityReport<'a>(pub &'a InfeasibilityReport);

/// Compact Markdown view of a report.
pub struct MarkdownInfeasibilityReport<'a>(pub &'a InfeasibilityReport);

impl<B> crate::solver::facade::SolverSession<B>
where
    B: crate::solver::session::BackendSession
        + crate::solver::session::SessionHealth
        + crate::solver::session::BackendMetadata,
{
    /// Analyze LP infeasibility without mutating the persistent solve session.
    pub fn analyze_infeasibility(
        &mut self,
        model: &Model,
        plan: &InfeasibilityPlan,
    ) -> Result<InfeasibilityReport, InfeasibilityError> {
        let canonical =
            model
                .take_snapshot()
                .map_err(|error| InfeasibilityError::InvalidUniverse {
                    reason: format!("could not snapshot model for analysis: {error}"),
                })?;

        if plan.scope == InfeasibilityScope::OriginalLp
            && canonical
                .variables
                .iter()
                .any(|variable| !matches!(variable.var_type, crate::model::VarType::Continuous))
        {
            return Err(InfeasibilityError::Unsupported {
                operation: "OriginalLp analysis requires a continuous LP; request LpRelaxation explicitly for a MIP".to_string(),
            });
        }

        let base_snapshot = if plan.overlay.is_some() {
            Some(self.compile_analysis_snapshot(model, &canonical, None)?)
        } else {
            None
        };
        let mut snapshot =
            self.compile_analysis_snapshot(model, &canonical, plan.overlay.as_ref())?;
        if plan.scope == InfeasibilityScope::LpRelaxation {
            // The analysis scope is semantic: an explicitly requested LP
            // relaxation must execute against continuous compiled columns,
            // including any integer columns generated by a formulation.
            // Keeping this transformation in the isolated analysis snapshot
            // prevents the persistent solve session or canonical model from
            // being changed and avoids relabelling a MIP solve as an LP.
            for variable in &mut snapshot.variables {
                variable.var_type = crate::model::VarType::Continuous;
            }
        } else if snapshot
            .variables
            .iter()
            .any(|variable| !matches!(variable.var_type, crate::model::VarType::Continuous))
        {
            return Err(InfeasibilityError::Unsupported {
                operation: "OriginalLp analysis compiled a non-continuous variable; request LpRelaxation explicitly".to_string(),
            });
        }
        if !plan.numerical_policy.feasibility_tolerance.is_finite()
            || plan.numerical_policy.feasibility_tolerance < 0.0
        {
            return Err(InfeasibilityError::Unsupported {
                operation: "feasibility_tolerance must be finite and non-negative".to_string(),
            });
        }
        let universe = match (base_snapshot.as_ref(), plan.overlay.as_ref()) {
            (Some(base), Some(overlay)) => {
                SemanticConflictUniverse::from_model_snapshot_with_overlay(
                    base,
                    &snapshot,
                    model,
                    &canonical,
                    overlay,
                    plan.scope,
                    plan.grouping,
                )?
            }
            _ => SemanticConflictUniverse::from_model_snapshot(
                &snapshot,
                &canonical,
                plan.scope,
                plan.grouping,
            )?,
        };
        let mut provider_chain = Vec::new();
        let mut warnings = Vec::new();
        let mut native = None;
        let mut native_result: Option<NativeConflict> = None;
        let mut seed = RestrictionSelection::all(&universe);

        let oracle = self
            .analysis_backend()
            .spawn_infeasibility_oracle(&snapshot, &universe)
            .map_err(|error| {
                if error.category == crate::solver::backend::ErrorCategory::Unsupported {
                    InfeasibilityError::Unsupported {
                        operation: error.message,
                    }
                } else {
                    InfeasibilityError::Backend(error)
                }
            })?;
        let mut analysis = AnalysisSession::new(oracle, &universe, plan.numerical_policy)?;
        let oracle_budget = OracleBudget {
            time_limit_ms: plan.budget.time_limit_ms,
            feasibility_tolerance: Some(plan.numerical_policy.feasibility_tolerance),
        };

        // The full semantic universe is authoritative. Native evidence is
        // only a seed after this check proves the complete model infeasible;
        // a feasible or unknown native subset can never overturn that fact.
        let full_outcome = if plan.budget.max_oracle_calls == Some(0) {
            None
        } else {
            Some(analysis.check(&seed, &oracle_budget)?)
        };
        let full_is_infeasible = matches!(
            full_outcome.as_ref(),
            Some(FeasibilityOutcome::ProvenInfeasible(_))
        );

        let native_requested = full_is_infeasible
            && !matches!(plan.mode, InfeasibilityMode::RomlPortable)
            && (matches!(plan.seed_policy, SeedPolicy::Adaptive)
                || matches!(
                    plan.mode,
                    InfeasibilityMode::NativeOnly | InfeasibilityMode::NativeThenRoml
                ));
        if native_requested {
            let request = NativeConflictRequest {
                compilation_id: snapshot.compilation_id,
                snapshot: snapshot.clone(),
            };
            match self.analysis_backend().native_conflict(&request) {
                Ok(evidence) => {
                    if evidence.compilation_id != snapshot.compilation_id {
                        return Err(InfeasibilityError::CompilationMismatch {
                            expected: snapshot.compilation_id,
                            actual: evidence.compilation_id,
                        });
                    }
                    native_result = Some(evidence.clone());
                    let native_ids: Vec<_> = universe
                        .atoms
                        .iter()
                        .filter(|atom| {
                            atom.compiled_restrictions
                                .iter()
                                .any(|restriction| evidence.members.contains(restriction))
                        })
                        .map(|atom| atom.id)
                        .collect();
                    if native_ids.is_empty() {
                        if matches!(plan.mode, InfeasibilityMode::NativeOnly) {
                            return Err(InfeasibilityError::Unsupported {
                                operation: "native IIS returned no mappable semantic members"
                                    .to_string(),
                            });
                        }
                        warnings.push(AnalysisWarning {
                            message: "native IIS returned no mappable members; portable full-universe seed used".to_string(),
                        });
                    } else {
                        let native_seed = RestrictionSelection {
                            compilation_id: snapshot.compilation_id,
                            atom_ids: native_ids,
                        };
                        let native_seed_outcome = if plan
                            .budget
                            .max_oracle_calls
                            .map(|limit| analysis.oracle_calls() < limit)
                            .unwrap_or(true)
                        {
                            Some(analysis.check(&native_seed, &oracle_budget)?)
                        } else {
                            None
                        };
                        match native_seed_outcome {
                            None => {
                                if matches!(plan.mode, InfeasibilityMode::NativeOnly) {
                                    seed = native_seed;
                                } else {
                                    warnings.push(AnalysisWarning {
                                        message: "oracle budget exhausted before native seed validation; portable reduction was not claimed".to_string(),
                                    });
                                }
                            }
                            Some(FeasibilityOutcome::ProvenInfeasible(_)) => seed = native_seed,
                            Some(FeasibilityOutcome::ProvenFeasible(_)) => {
                                if matches!(
                                    plan.mode,
                                    InfeasibilityMode::NativeOnly
                                        | InfeasibilityMode::NativeThenRoml
                                ) {
                                    return Err(InfeasibilityError::VerificationFailure {
                                        reason: "native provider seed was proven feasible"
                                            .to_string(),
                                    });
                                }
                                warnings.push(AnalysisWarning {
                                    message: "native seed was feasible; discarded in favor of the proven-infeasible full universe".to_string(),
                                });
                            }
                            Some(FeasibilityOutcome::Unknown(reason)) => {
                                if matches!(
                                    plan.mode,
                                    InfeasibilityMode::NativeOnly
                                        | InfeasibilityMode::NativeThenRoml
                                ) {
                                    return Err(InfeasibilityError::VerificationFailure {
                                        reason: format!("native provider seed was not proven infeasible: {reason:?}"),
                                    });
                                }
                                warnings.push(AnalysisWarning {
                                    message: "native seed was not proven infeasible; discarded in favor of the proven-infeasible full universe".to_string(),
                                });
                            }
                        }
                    }
                    provider_chain.push(AnalysisProviderRecord {
                        name: "HiGHS native IIS seed".to_string(),
                    });
                    native = Some(NativeConflictEvidence {
                        provider: "HiGHS native IIS".to_string(),
                        evidence: evidence.evidence.clone(),
                    });

                    if matches!(plan.mode, InfeasibilityMode::NativeOnly) {
                        let native_member_ids: Vec<_> = universe
                            .atoms
                            .iter()
                            .filter(|atom| {
                                atom.compiled_restrictions
                                    .iter()
                                    .any(|restriction| evidence.members.contains(restriction))
                            })
                            .map(|atom| atom.id)
                            .collect();
                        let members = report_members(&universe, &native_member_ids, &evidence);
                        return Ok(InfeasibilityReport {
                            model_lineage: model.lineage(),
                            model_instance: model.instance(),
                            model_revision: canonical.revision,
                            compilation_id: snapshot.compilation_id,
                            backend: BackendIdentity {
                                name: self.analysis_backend().backend_name().to_string(),
                                version: self.analysis_backend().version().to_string(),
                            },
                            provider_chain,
                            scope: plan.scope,
                            candidate_universe: CandidateUniverseSummary {
                                atom_count: universe.atoms.len(),
                                grouping: universe.grouping,
                            },
                            outcome: InfeasibilityOutcome::Conflict,
                            completion: AnalysisCompletion::Complete,
                            guarantee: ConflictGuarantee::NativeReported,
                            oracle_strength: FeasibilityProofStrength::Unknown,
                            numerical_policy: plan.numerical_policy,
                            members,
                            native_evidence: native,
                            statistics: InfeasibilityStatistics {
                                oracle_calls: analysis.oracle_calls(),
                                ..InfeasibilityStatistics::default()
                            },
                            warnings,
                        });
                    }
                }
                Err(error) if matches!(plan.mode, InfeasibilityMode::Auto) => {
                    warnings.push(AnalysisWarning {
                        message: format!(
                            "native provider unavailable; portable fallback: {}",
                            error.message
                        ),
                    });
                }
                Err(error) => {
                    return Err(
                        if error.category == crate::solver::backend::ErrorCategory::Unsupported {
                            InfeasibilityError::Unsupported {
                                operation: error.message,
                            }
                        } else {
                            InfeasibilityError::Backend(error)
                        },
                    );
                }
            }
        }

        provider_chain.push(AnalysisProviderRecord {
            name: "ROML semantic reducer".to_string(),
        });
        provider_chain.push(AnalysisProviderRecord {
            name: "fresh semantic verifier".to_string(),
        });
        let reduced = crate::solver::reducer::reduce_with_limits_and_policy(
            &mut analysis,
            &universe,
            seed,
            oracle_budget,
            plan.budget.max_oracle_calls,
            plan.budget.max_iterations,
            plan.reduction,
        )?;
        let (outcome, guarantee, oracle_strength, members, completion, statistics) = match reduced {
            crate::solver::reducer::ReductionOutcome::NoConflict => (
                InfeasibilityOutcome::NoConflict,
                ConflictGuarantee::None,
                FeasibilityProofStrength::Proven,
                Vec::new(),
                AnalysisCompletion::Complete,
                InfeasibilityStatistics {
                    oracle_calls: analysis.oracle_calls(),
                    ..InfeasibilityStatistics::default()
                },
            ),
            crate::solver::reducer::ReductionOutcome::NoConflictProof => (
                InfeasibilityOutcome::NoConflictProof,
                ConflictGuarantee::None,
                FeasibilityProofStrength::Unknown,
                Vec::new(),
                completion_for_analysis(
                    full_outcome.as_ref(),
                    analysis.oracle_calls(),
                    plan.budget.max_oracle_calls,
                ),
                InfeasibilityStatistics {
                    oracle_calls: analysis.oracle_calls(),
                    ..InfeasibilityStatistics::default()
                },
            ),
            crate::solver::reducer::ReductionOutcome::Conflict(conflict) => (
                InfeasibilityOutcome::Conflict,
                conflict.guarantee,
                if conflict.guarantee == ConflictGuarantee::Irreducible {
                    FeasibilityProofStrength::Proven
                } else {
                    FeasibilityProofStrength::Limited
                },
                report_members(
                    &universe,
                    &conflict.members,
                    native_result.as_ref().unwrap_or(&NativeConflict {
                        compilation_id: snapshot.compilation_id,
                        members: Vec::new(),
                        evidence: Vec::new(),
                    }),
                ),
                if conflict.statistics.budget_exhausted {
                    if plan
                        .budget
                        .max_oracle_calls
                        .is_some_and(|limit| analysis.oracle_calls() >= limit)
                    {
                        AnalysisCompletion::OracleCallLimit
                    } else {
                        AnalysisCompletion::IterationLimit
                    }
                } else {
                    AnalysisCompletion::Complete
                },
                InfeasibilityStatistics {
                    oracle_calls: conflict.statistics.oracle_calls,
                    iterations: conflict.statistics.iterations,
                    fresh_verification_checks: conflict.statistics.fresh_verification_checks,
                },
            ),
        };

        Ok(InfeasibilityReport {
            model_lineage: model.lineage(),
            model_instance: model.instance(),
            model_revision: canonical.revision,
            compilation_id: snapshot.compilation_id,
            backend: BackendIdentity {
                name: self.analysis_backend().backend_name().to_string(),
                version: self.analysis_backend().version().to_string(),
            },
            provider_chain,
            scope: plan.scope,
            candidate_universe: CandidateUniverseSummary {
                atom_count: universe.atoms.len(),
                grouping: universe.grouping,
            },
            outcome,
            completion,
            guarantee,
            oracle_strength,
            numerical_policy: plan.numerical_policy,
            members,
            native_evidence: native,
            statistics,
            warnings,
        })
    }
}

fn completion_for_analysis(
    full_outcome: Option<&FeasibilityOutcome>,
    oracle_calls: u64,
    max_oracle_calls: Option<u64>,
) -> AnalysisCompletion {
    if max_oracle_calls.is_some_and(|limit| oracle_calls >= limit) {
        return AnalysisCompletion::OracleCallLimit;
    }
    match full_outcome {
        Some(FeasibilityOutcome::Unknown(UnknownReason::TimeLimit)) => {
            AnalysisCompletion::TimeLimit
        }
        Some(FeasibilityOutcome::Unknown(UnknownReason::IterationLimit)) => {
            AnalysisCompletion::IterationLimit
        }
        Some(FeasibilityOutcome::Unknown(UnknownReason::NodeLimit)) => {
            AnalysisCompletion::NodeLimit
        }
        Some(FeasibilityOutcome::Unknown(UnknownReason::Interrupted)) => {
            AnalysisCompletion::Interrupted
        }
        Some(FeasibilityOutcome::Unknown(UnknownReason::Numerical)) => {
            AnalysisCompletion::Numerical
        }
        Some(FeasibilityOutcome::Unknown(UnknownReason::BackendError)) => {
            AnalysisCompletion::BackendFailure
        }
        Some(FeasibilityOutcome::Unknown(_)) => AnalysisCompletion::BackendFailure,
        _ => AnalysisCompletion::Complete,
    }
}

fn report_members(
    universe: &SemanticConflictUniverse,
    ids: &[ConflictAtomId],
    native: &NativeConflict,
) -> Vec<ConflictMember> {
    let mut members: Vec<_> = universe
        .atoms
        .iter()
        .filter(|atom| ids.contains(&atom.id))
        .map(|atom| ConflictMember {
            atom_id: atom.id,
            declaration: atom.snapshot.clone(),
            compiled_evidence: atom
                .compiled_restrictions
                .iter()
                .map(|reference| CompiledRestrictionEvidence {
                    reference: *reference,
                    native_membership: native
                        .evidence
                        .iter()
                        .find(|evidence| evidence.restriction == *reference)
                        .map(|evidence| evidence.membership),
                    native_bound: native
                        .evidence
                        .iter()
                        .find(|evidence| evidence.restriction == *reference)
                        .and_then(|evidence| evidence.bound),
                })
                .collect(),
        })
        .collect();
    members.sort_by_key(|member| member.atom_id);
    members
}
