//! LP infeasibility analysis contracts.
//!
//! The first Phase 29 slice freezes the public vocabulary and the typed
//! tri-state feasibility rule. Execution machinery is added in later slices.

use std::fmt;

use crate::compiler::backend_ir::{
    BackendSnapshot, CompilationId, CompiledConstraintId, CompiledEntityRef, CompiledVariableId,
};
use crate::compiler::origin::{EntityOrigin, GeneratedRole};
use crate::compiler::report::BackendIdentity;
use crate::construct::Construct;
use crate::identity::{ModelInstanceId, ModelLineageId};
use crate::model::{Constraint, Model, Variable};
use crate::revision::ModelRevision;
use crate::solver::backend::{BackendError, TerminationStatus};

/// Selects the provider strategy for LP infeasibility analysis.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InfeasibilityMode {
    /// Prefer a qualified native seed and reduce it semantically, with a
    /// portable fallback when native analysis is unavailable.
    Auto,
    /// Use only the solver-agnostic ROML reducer.
    RomlPortable,
    /// Require a qualified native provider and never fall back.
    NativeOnly,
    /// Require native seed acquisition, followed by ROML semantic reduction.
    NativeThenRoml,
}

/// Selects which LP model scope is analyzed.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InfeasibilityScope {
    /// Analyze the original continuous LP model.
    OriginalLp,
    /// Analyze an explicitly requested LP relaxation of a MIP model.
    LpRelaxation,
}

/// Selects how semantic restrictions are grouped into candidate atoms.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConflictGrouping {
    /// Keep each independently toggleable semantic restriction separate.
    Individual,
    /// Keep restrictions generated by one semantic construct together.
    ByConstruct,
}

/// Selects the initial conflict seed strategy.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SeedPolicy {
    /// Use the cheapest qualified seed, then fall back through the provider
    /// chain defined by the analysis mode.
    Adaptive,
    /// Start with every semantic restriction in the requested universe.
    FullUniverse,
}

/// Selects the semantic deletion strategy.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReductionPolicy {
    /// Use adaptive chunk deletion followed by exact single-atom polishing.
    Adaptive,
    /// Use exact single-atom deletion only.
    SingleAtom,
}

/// Bounds the work performed by one infeasibility analysis.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct AnalysisBudget {
    /// Maximum number of feasibility-oracle calls, if bounded.
    pub max_oracle_calls: Option<u64>,
    /// Maximum number of reducer iterations, if bounded.
    pub max_iterations: Option<u64>,
}

/// Controls numerical tolerances used by the feasibility oracle and verifier.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct AnalysisNumericalPolicy {
    /// Feasibility tolerance used by qualified oracle checks.
    pub feasibility_tolerance: f64,
}

impl Default for AnalysisNumericalPolicy {
    fn default() -> Self {
        Self {
            feasibility_tolerance: 1e-7,
        }
    }
}

/// Complete request for one LP infeasibility analysis.
#[derive(Clone, Debug, PartialEq)]
pub struct InfeasibilityPlan {
    /// Provider strategy.
    pub mode: InfeasibilityMode,
    /// Requested LP scope.
    pub scope: InfeasibilityScope,
    /// Semantic atom grouping.
    pub grouping: ConflictGrouping,
    /// Initial seed policy.
    pub seed_policy: SeedPolicy,
    /// Reduction policy.
    pub reduction: ReductionPolicy,
    /// Work budget.
    pub budget: AnalysisBudget,
    /// Numerical policy.
    pub numerical_policy: AnalysisNumericalPolicy,
}

impl InfeasibilityPlan {
    /// Build the default portable analysis plan for the original LP.
    pub fn portable_lp() -> Self {
        Self {
            mode: InfeasibilityMode::RomlPortable,
            scope: InfeasibilityScope::OriginalLp,
            grouping: ConflictGrouping::Individual,
            seed_policy: SeedPolicy::Adaptive,
            reduction: ReductionPolicy::Adaptive,
            budget: AnalysisBudget::default(),
            numerical_policy: AnalysisNumericalPolicy::default(),
        }
    }
}

/// Evidence that an oracle proved the selected restrictions feasible.
#[derive(Clone, Debug, PartialEq)]
pub struct FeasibilityEvidence {
    /// Backend termination status supporting the proof.
    pub termination: TerminationStatus,
}

/// Evidence that an oracle proved the selected restrictions infeasible.
#[derive(Clone, Debug, PartialEq)]
pub struct InfeasibilityEvidence {
    /// Backend termination status supporting the proof.
    pub termination: TerminationStatus,
}

/// Reason an oracle could not prove either feasibility result.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UnknownReason {
    /// The backend reported an infeasible-or-unbounded ambiguity.
    Ambiguous,
    /// The backend reported unboundedness without a feasibility proof under
    /// the analysis policy.
    Unbounded,
    /// A time, iteration, or node limit prevented a proof.
    Limit,
    /// The backend was interrupted.
    Interrupted,
    /// Numerical behavior prevented a reliable proof.
    Numerical,
    /// The backend returned an operational error.
    BackendError,
    /// The backend returned an unclassified status.
    Unclassified,
}

/// Which side of a two-sided semantic restriction is represented.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BoundSide {
    /// Lower side.
    Lower,
    /// Upper side.
    Upper,
}

/// Semantic class of one conflict atom.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ConflictAtomKind {
    /// One side of a user constraint.
    ConstraintSide(BoundSide),
    /// One variable bound side.
    VariableBound(BoundSide),
    /// A persistent fixing contribution.
    PersistentFixing,
    /// A solve-scoped lock contribution.
    SolveLock,
    /// A temporary fixing contribution.
    TemporaryFixing,
    /// A grouped generated semantic construct.
    GroupedConstruct,
    /// Reserved function-in-set semantic member for later nonlinear work.
    FunctionInSet,
}

/// Original semantic origin of one restriction atom.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum ConflictOrigin {
    /// A user constraint side.
    ConstraintSide {
        /// User constraint.
        constraint: Constraint,
        /// Side represented.
        side: BoundSide,
    },
    /// A user variable bound side.
    VariableBound {
        /// User variable.
        variable: Variable,
        /// Side represented.
        side: BoundSide,
    },
    /// A persistent fixing on a variable.
    PersistentFixing {
        /// User variable.
        variable: Variable,
    },
    /// A solve lock on a variable.
    SolveLock {
        /// User variable.
        variable: Variable,
    },
    /// A temporary fixing on a variable.
    TemporaryFixing {
        /// User variable.
        variable: Variable,
    },
    /// A generated restriction grouped under one semantic construct.
    GroupedConstruct {
        /// Semantic construct.
        construct: Construct,
        /// Generated role.
        role: GeneratedRole,
    },
    /// A future function-in-set member.
    FunctionInSet {
        /// Function-in-set origin.
        origin: EntityOrigin,
    },
}

/// Immutable historical values retained for one conflict member.
#[derive(Clone, Debug, PartialEq)]
pub struct ConflictMemberSnapshot {
    /// Semantic origin.
    pub origin: ConflictOrigin,
    /// Optional source name.
    pub name: Option<String>,
    /// Bound value represented by this member, when applicable.
    pub value: Option<f64>,
}

/// Action used to toggle one semantic restriction.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RestrictionToggleAction {
    /// Disable the atom from the isolated analysis session.
    Disable,
    /// Restore the atom and its lower bound contribution layer.
    Restore,
}

/// Exact toggle operation for one semantic atom.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RestrictionTogglePlan {
    /// Atom affected by the operation.
    pub atom_id: ConflictAtomId,
    /// Operation to apply.
    pub action: RestrictionToggleAction,
}

/// The only outcomes an isolated feasibility oracle may return.
#[non_exhaustive]
#[derive(Clone, Debug, PartialEq)]
pub enum FeasibilityOutcome {
    /// Feasibility was proven.
    ProvenFeasible(FeasibilityEvidence),
    /// Infeasibility was proven.
    ProvenInfeasible(InfeasibilityEvidence),
    /// No proof was obtained.
    Unknown(UnknownReason),
}

/// Classify a backend termination without converting uncertainty to conflict.
pub fn classify_feasibility(status: TerminationStatus) -> FeasibilityOutcome {
    match status {
        TerminationStatus::Optimal | TerminationStatus::Feasible => {
            FeasibilityOutcome::ProvenFeasible(FeasibilityEvidence {
                termination: status,
            })
        }
        TerminationStatus::Infeasible => {
            FeasibilityOutcome::ProvenInfeasible(InfeasibilityEvidence {
                termination: status,
            })
        }
        TerminationStatus::InfeasibleOrUnbounded => {
            FeasibilityOutcome::Unknown(UnknownReason::Ambiguous)
        }
        TerminationStatus::Unbounded => FeasibilityOutcome::Unknown(UnknownReason::Unbounded),
        TerminationStatus::TimeLimit
        | TerminationStatus::IterationLimit
        | TerminationStatus::NodeLimit => FeasibilityOutcome::Unknown(UnknownReason::Limit),
        TerminationStatus::Interrupted => FeasibilityOutcome::Unknown(UnknownReason::Interrupted),
        TerminationStatus::NumericalIssue => FeasibilityOutcome::Unknown(UnknownReason::Numerical),
        TerminationStatus::Error => FeasibilityOutcome::Unknown(UnknownReason::BackendError),
        TerminationStatus::Unknown => FeasibilityOutcome::Unknown(UnknownReason::Unclassified),
    }
}

/// Error returned by infeasibility analysis.
#[derive(Clone, Debug, PartialEq)]
pub enum InfeasibilityError {
    /// The requested provider or model scope is not qualified.
    Unsupported {
        /// Operation that was not qualified.
        operation: String,
    },
    /// A mapping or operation used a different exact compiled state.
    CompilationMismatch {
        /// Expected compiled state.
        expected: CompilationId,
        /// Supplied compiled state.
        actual: CompilationId,
    },
    /// A backend operation failed.
    Backend(BackendError),
    /// The compiled snapshot cannot produce a complete semantic universe.
    InvalidUniverse {
        /// Why the universe is invalid.
        reason: String,
    },
}

impl fmt::Display for InfeasibilityError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Unsupported { operation } => {
                write!(f, "unsupported infeasibility operation: {operation}")
            }
            Self::CompilationMismatch { expected, actual } => {
                write!(
                    f,
                    "infeasibility compilation mismatch: expected {expected:?}, got {actual:?}"
                )
            }
            Self::Backend(error) => error.fmt(f),
            Self::InvalidUniverse { reason } => {
                write!(f, "invalid semantic conflict universe: {reason}")
            }
        }
    }
}

impl std::error::Error for InfeasibilityError {}

/// Guarantee attached to a conflict report.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConflictGuarantee {
    /// No conflict guarantee was established.
    None,
    /// Semantic irreducibility under the recorded universe, oracle, and
    /// numerical policy; never minimum cardinality.
    Irreducible,
    /// The backend reported a native conflict that was not semantically
    /// reduced to an irreducibility claim.
    NativeReported,
}

/// Whether the analysis finished all required verification work.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AnalysisCompletion {
    /// Reduction and fresh verification completed.
    Complete,
    /// A work limit stopped the analysis.
    Limit,
    /// The analysis was interrupted.
    Interrupted,
    /// Numerical behavior stopped the analysis.
    Numerical,
    /// A backend failure stopped the analysis.
    BackendFailure,
}

/// Result classification independent of completion and guarantee.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InfeasibilityOutcome {
    /// The requested model was proven feasible.
    NoConflict,
    /// A conflict was proven and reported.
    Conflict,
    /// Initial feasibility was unknown, so no no-conflict claim is made.
    NoConflictProof,
}

/// Strength of the feasibility oracle used by the report.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FeasibilityProofStrength {
    /// Every required check was proven.
    Proven,
    /// At least one check was limited or otherwise weaker.
    Limited,
    /// No proof was available.
    Unknown,
}

/// Provider record retained in report history.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AnalysisProviderRecord {
    /// Provider label.
    pub name: String,
}

/// Candidate-universe summary retained in report history.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CandidateUniverseSummary {
    /// Number of semantic candidate atoms.
    pub atom_count: usize,
}

/// One semantic conflict member.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConflictMember {
    /// Stable semantic atom identifier.
    pub atom_id: ConflictAtomId,
}

/// Native membership evidence retained without promoting its guarantee.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NativeConflictEvidence {
    /// Provider label.
    pub provider: String,
}

/// Counters collected during analysis.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct InfeasibilityStatistics {
    /// Number of oracle calls.
    pub oracle_calls: u64,
}

/// Warning retained in a report.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AnalysisWarning {
    /// Stable warning text.
    pub message: String,
}

/// Canonical structured infeasibility report.
#[derive(Clone, Debug, PartialEq)]
pub struct InfeasibilityReport {
    /// Model lineage.
    pub model_lineage: ModelLineageId,
    /// Exact model instance.
    pub model_instance: ModelInstanceId,
    /// Model revision analyzed.
    pub model_revision: ModelRevision,
    /// Exact compilation identity analyzed.
    pub compilation_id: CompilationId,
    /// Backend identity.
    pub backend: BackendIdentity,
    /// Provider chain.
    pub provider_chain: Vec<AnalysisProviderRecord>,
    /// Requested scope.
    pub scope: InfeasibilityScope,
    /// Candidate universe summary.
    pub candidate_universe: CandidateUniverseSummary,
    /// Outcome independent of completion.
    pub outcome: InfeasibilityOutcome,
    /// Completion state.
    pub completion: AnalysisCompletion,
    /// Conflict guarantee.
    pub guarantee: ConflictGuarantee,
    /// Oracle proof strength.
    pub oracle_strength: FeasibilityProofStrength,
    /// Numerical policy.
    pub numerical_policy: AnalysisNumericalPolicy,
    /// Semantic members.
    pub members: Vec<ConflictMember>,
    /// Optional native evidence.
    pub native_evidence: Option<NativeConflictEvidence>,
    /// Analysis statistics.
    pub statistics: InfeasibilityStatistics,
    /// Warnings.
    pub warnings: Vec<AnalysisWarning>,
}

/// Stable opaque identifier for a semantic conflict atom.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ConflictAtomId(pub u64);

/// Reference to one compiled restriction.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CompiledRestrictionRef {
    /// Lower side of a compiled row.
    ConstraintLower(CompiledConstraintId),
    /// Upper side of a compiled row.
    ConstraintUpper(CompiledConstraintId),
    /// Lower bound side of a compiled variable.
    VariableLower(CompiledVariableId),
    /// Upper bound side of a compiled variable.
    VariableUpper(CompiledVariableId),
    /// A compiled entity generated by a grouped semantic construct.
    Entity(CompiledEntityRef),
}

/// Semantic restriction universe used by a reducer and oracle.
#[derive(Clone, Debug, PartialEq)]
pub struct SemanticConflictUniverse {
    /// Exact compiled state this universe belongs to.
    pub compilation_id: CompilationId,
    /// Semantic atoms.
    pub atoms: Vec<SemanticRestrictionAtom>,
    /// Compiled restrictions represented by the atoms.
    pub compiled_restrictions: Vec<CompiledRestrictionRef>,
    /// Grouping policy used to form atoms.
    pub grouping: ConflictGrouping,
}

/// One semantically toggleable restriction atom.
#[derive(Clone, Debug, PartialEq)]
pub struct SemanticRestrictionAtom {
    /// Stable atom identifier.
    pub id: ConflictAtomId,
    /// Semantic class.
    pub kind: ConflictAtomKind,
    /// Original semantic origin.
    pub origin: ConflictOrigin,
    /// Compiled restrictions covered by this atom.
    pub compiled_restrictions: Vec<CompiledRestrictionRef>,
    /// Disable operation.
    pub disable: RestrictionTogglePlan,
    /// Restore operation.
    pub restore: RestrictionTogglePlan,
    /// Historical member data.
    pub snapshot: ConflictMemberSnapshot,
}

/// Selection of atoms to retain for one oracle check.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RestrictionSelection {
    /// Exact universe compilation identity.
    pub compilation_id: CompilationId,
    /// Selected atom identifiers.
    pub atom_ids: Vec<ConflictAtomId>,
}

/// Oracle budget for one feasibility check.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct OracleBudget {
    /// Optional backend time limit in milliseconds.
    pub time_limit_ms: Option<u64>,
}

/// Feasibility oracle used by the portable reducer.
pub trait FeasibilityOracle {
    /// Exact compiled state checked by this oracle.
    fn compilation_id(&self) -> CompilationId;

    /// Check one semantic restriction selection.
    fn check(
        &mut self,
        selection: &RestrictionSelection,
        budget: &OracleBudget,
    ) -> Result<FeasibilityOutcome, BackendError>;
}

/// Native conflict request passed through a qualified backend boundary.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NativeConflictRequest {
    /// Exact compiled state requested.
    pub compilation_id: CompilationId,
}

/// Native compiled-membership conflict result.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NativeConflict {
    /// Exact compiled state producing the evidence.
    pub compilation_id: CompilationId,
    /// Compiled restrictions reported by the provider.
    pub members: Vec<CompiledRestrictionRef>,
}

/// Optional backend capability boundary for infeasibility analysis.
pub trait InfeasibilityOracleFactory {
    /// Oracle type created by this backend.
    type Oracle: FeasibilityOracle;

    /// Create an isolated oracle over one exact backend snapshot.
    fn spawn_infeasibility_oracle(
        &self,
        snapshot: &BackendSnapshot,
        universe: &SemanticConflictUniverse,
    ) -> Result<Self::Oracle, BackendError>;

    /// Request native compiled-membership evidence.
    fn native_conflict(
        &self,
        request: &NativeConflictRequest,
    ) -> Result<NativeConflict, BackendError>;
}

/// Compact structured-text view of a report.
pub struct TextInfeasibilityReport<'a>(pub &'a InfeasibilityReport);

/// Compact Markdown view of a report.
pub struct MarkdownInfeasibilityReport<'a>(pub &'a InfeasibilityReport);

impl<B> crate::solver::facade::SolverSession<B>
where
    B: crate::solver::session::BackendSession
        + crate::solver::session::SessionHealth
        + crate::solver::session::BackendMetadata,
{
    /// Analyze LP infeasibility without mutating the persistent solve session.
    pub fn analyze_infeasibility(
        &mut self,
        _model: &Model,
        _plan: &InfeasibilityPlan,
    ) -> Result<InfeasibilityReport, InfeasibilityError> {
        Err(InfeasibilityError::Unsupported {
            operation: "LP infeasibility analysis is not implemented yet".to_string(),
        })
    }
}
