//! `P34_PRIMITIVE_PARAMETER_UPDATE_V1` (contract §4): deterministic
//! `set_parameter + solve` benchmark.
//!
//! Model (fixed constants, no network, no customer data):
//! - 512 continuous variables, bounds `[0, 100]`;
//! - 512 linear `>=` rows, 8 deterministic nonzeros per row (4096 nnz),
//!   generated by xorshift with fixed seed `0x524F4D4C`;
//! - one scalar parameter combined into 64 coefficient cells;
//! - deterministic linear minimization with finite coefficients.
//! - bundled HiGHS, output off, threads = 1.
//!
//! Procedure: build once, one initial solve, 20 warmup update+solve
//! attempts, then 200 measured attempts. Each attempt sets the parameter to
//! `1.0 + 0.25 * ((i * 7) % 9)` and solves. Reports wall-time median/p25/p75
//! plus synchronization classification counts as compact JSON on stdout.
//!
//! The driver uses only APIs present in both the current tree and the
//! historical baseline `4d111cc` (see `adapter_4d111cc.patch` for the exact
//! mechanical differences); the mathematical workload is identical.

use std::time::Instant;

use roml::{
    continuous, ConstraintExprExt, LinExpr, Model, Sense, SolveOptions, SolveStatus, SolverSession,
    ValueExpr,
};
use roml_highs::HighsSession;

const VARIABLES: usize = 512;
const ROWS: usize = 512;
const NNZ_PER_ROW: usize = 8;
const PARAM_CELLS: usize = 64;
const RNG_SEED: u64 = 0x524F4D4C;

fn xorshift(state: &mut u64) -> u64 {
    let mut x = *state;
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    *state = x;
    x
}

fn percentile(sorted_ms: &[f64], q: f64) -> f64 {
    if sorted_ms.is_empty() {
        return 0.0;
    }
    let rank = q * ((sorted_ms.len() - 1) as f64);
    let lower = rank.floor() as usize;
    let upper = rank.ceil() as usize;
    if lower == upper {
        sorted_ms[lower]
    } else {
        sorted_ms[lower] + (rank - lower as f64) * (sorted_ms[upper] - sorted_ms[lower])
    }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut warmups = 20usize;
    let mut measured = 200usize;
    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--warmups" => {
                warmups = args[i + 1].parse().expect("warmup count");
                i += 2;
            }
            "--measured" => {
                measured = args[i + 1].parse().expect("measured count");
                i += 2;
            }
            other => panic!("unknown argument {other}"),
        }
    }

    let mut rng = RNG_SEED;
    let mut model = Model::new();
    let mut vars = Vec::with_capacity(VARIABLES);
    for _ in 0..VARIABLES {
        vars.push(
            model
                .add_variable(continuous().bounds(0.0, 100.0))
                .expect("variable"),
        );
    }
    let mut rows = Vec::with_capacity(ROWS);
    for r in 0..ROWS {
        let mut expr = LinExpr::new();
        for _ in 0..NNZ_PER_ROW {
            let v = vars[(xorshift(&mut rng) as usize) % VARIABLES];
            expr = expr + LinExpr::from(v);
        }
        // Deterministic right-hand sides in [20, 26]; every row is feasible
        // within [0, 100]^8 and the minimization stays bounded below by 0.
        let rhs = 20.0 + ((r * 13) % 7) as f64;
        rows.push(model.add_constraint(expr.ge(rhs)).expect("row"));
    }
    // Deterministic positive linear minimization: optimum is finite and
    // moves as the parameter scales cells.
    let obj = model.add_objective(Sense::Minimize);
    for v in &vars {
        model
            .add_objective_coefficient(obj, *v, 1.0)
            .expect("objective cell");
    }
    model.set_active_objective(obj).expect("active objective");

    // One scalar parameter combined into exactly 64 coefficient cells.
    let param = model.add_parameter(1.0).expect("parameter");
    for j in 0..PARAM_CELLS {
        let r = (j * 8) % ROWS;
        let v = vars[(8 * r + (j % 8)) % VARIABLES];
        model
            .add_constraint_coefficient(rows[r], v, ValueExpr::param(param))
            .expect("parameter cell");
    }

    let mut session = SolverSession::new(
        HighsSession::try_new().expect("bundled HiGHS available"),
    );
    let options = SolveOptions::new().threads(1).output(false);
    let first = session
        .solve_with(&mut model, options.clone())
        .expect("initial solve");
    assert_eq!(first.status(), SolveStatus::Optimal);
    let first_objective = first.objective_value().expect("initial objective");
    assert!(first_objective.is_finite());

    let mut sync_kinds = std::collections::BTreeMap::new();
    let mut run = |attempt: usize| -> f64 {
        // Deterministic finite parameter stream in [1.0, 3.0].
        let value = 1.0 + 0.25 * (((attempt * 7) % 9) as f64);
        model.set_parameter(param, value).expect("parameter update");
        let start = Instant::now();
        let solution = session
            .solve_with(&mut model, options.clone())
            .expect("update+solve must stay optimal");
        let elapsed_ms = start.elapsed().as_secs_f64() * 1000.0;
        assert_eq!(solution.status(), SolveStatus::Optimal);
        *sync_kinds
            .entry(format!("{:?}", solution.metadata().synchronization))
            .or_insert(0usize) += 1;
        elapsed_ms
    };

    for attempt in 0..warmups {
        run(attempt);
    }
    let mut times_ms = Vec::with_capacity(measured);
    for attempt in 0..measured {
        times_ms.push(run(warmups + attempt));
    }
    times_ms.sort_by(|a, b| a.partial_cmp(b).unwrap());
    let median = percentile(&times_ms, 0.5);
    let p25 = percentile(&times_ms, 0.25);
    let p75 = percentile(&times_ms, 0.75);

    let sync_json = sync_kinds
        .iter()
        .map(|(k, v)| format!("\"{k}\":{v}"))
        .collect::<Vec<_>>()
        .join(",");
    println!(
        "{{\"fixture\":\"P34_PRIMITIVE_PARAMETER_UPDATE_V1\",\"harness_version\":\"{}\",\"variables\":{},\"rows\":{},\"nnz\":{},\"param_cells\":{},\"warmups\":{},\"measured\":{},\"median_ms\":{:.6},\"p25_ms\":{:.6},\"p75_ms\":{:.6},\"initial_objective\":{:.6},\"sync\":{{{}}}}}",
        env!("CARGO_PKG_VERSION"),
        VARIABLES,
        ROWS,
        ROWS * NNZ_PER_ROW,
        PARAM_CELLS,
        warmups,
        measured,
        median,
        p25,
        p75,
        first_objective,
        sync_json,
    );
}
