"""Type stubs for roml._native (MPY-02 scalar API; extended per phase)."""

from __future__ import annotations

from enum import Enum
from typing import Any, overload

def version() -> str: ...

class RomlError(Exception):
    code: str | None = ...

class InvalidModelError(RomlError, ValueError): ...
class InvalidHandleError(RomlError, ValueError): ...
class ModelMismatchError(RomlError, ValueError): ...
class ShapeError(RomlError, ValueError): ...
class UnsupportedExpressionError(RomlError, TypeError): ...
class UnsupportedFeatureError(RomlError): ...
class ModelBusyError(RomlError): ...
class SessionBusyError(RomlError): ...
class ClosedSessionError(RomlError): ...
class SolverError(RomlError):
    category: str
    health_effect: str
    requires_rebuild: bool
    native_code: int | None
class NoSolutionError(RomlError): ...
class MissingValueError(RomlError): ...
class UnavailableDiagnosticError(RomlError): ...

class SolveStatus(Enum):
    Unknown = ...
    Optimal = ...
    Feasible = ...
    Infeasible = ...
    Unbounded = ...
    InfeasibleOrUnbounded = ...
    TimeLimit = ...
    IterationLimit = ...
    NodeLimit = ...
    Interrupted = ...
    Numerical = ...
    Error = ...
    UNKNOWN: SolveStatus
    OPTIMAL: SolveStatus
    FEASIBLE: SolveStatus
    INFEASIBLE: SolveStatus
    UNBOUNDED: SolveStatus
    INFEASIBLE_OR_UNBOUNDED: SolveStatus
    TIME_LIMIT: SolveStatus
    ITERATION_LIMIT: SolveStatus
    NODE_LIMIT: SolveStatus
    INTERRUPTED: SolveStatus
    NUMERICAL: SolveStatus
    ERROR: SolveStatus

class Var:
    @overload
    def __add__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __add__(self, other: Any) -> Expr: ...
    @overload
    def __radd__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __radd__(self, other: Any) -> Expr: ...
    @overload
    def __sub__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __sub__(self, other: Any) -> Expr: ...
    @overload
    def __rsub__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __rsub__(self, other: Any) -> Expr: ...
    @overload
    def __mul__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __mul__(self, other: Any) -> Expr: ...
    @overload
    def __rmul__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __rmul__(self, other: Any) -> Expr: ...
    @overload
    def __le__(self, other: VarArray | ParamArray | ExprArray) -> ComparisonArray: ...
    @overload
    def __le__(self, other: Any) -> Comparison: ...
    @overload
    def __ge__(self, other: VarArray | ParamArray | ExprArray) -> ComparisonArray: ...
    @overload
    def __ge__(self, other: Any) -> Comparison: ...
    @overload
    def __eq__(self, other: VarArray | ParamArray | ExprArray) -> ComparisonArray: ...
    @overload
    def __eq__(self, other: Any) -> Comparison: ...
    def __truediv__(self, other: float) -> Expr: ...

class Param:
    @overload
    def __add__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __add__(self, other: Any) -> Expr: ...
    @overload
    def __radd__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __radd__(self, other: Any) -> Expr: ...
    @overload
    def __sub__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __sub__(self, other: Any) -> Expr: ...
    @overload
    def __rsub__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __rsub__(self, other: Any) -> Expr: ...
    @overload
    def __mul__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __mul__(self, other: Any) -> Expr: ...
    @overload
    def __rmul__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __rmul__(self, other: Any) -> Expr: ...
    def __truediv__(self, other: float) -> Expr: ...

class Expr:
    @overload
    def __add__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __add__(self, other: Any) -> Expr: ...
    @overload
    def __radd__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __radd__(self, other: Any) -> Expr: ...
    @overload
    def __sub__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __sub__(self, other: Any) -> Expr: ...
    @overload
    def __rsub__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __rsub__(self, other: Any) -> Expr: ...
    @overload
    def __mul__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __mul__(self, other: Any) -> Expr: ...
    @overload
    def __rmul__(self, other: VarArray | ParamArray | ExprArray) -> ExprArray: ...
    @overload
    def __rmul__(self, other: Any) -> Expr: ...
    @overload
    def __le__(self, other: VarArray | ParamArray | ExprArray) -> ComparisonArray: ...
    @overload
    def __le__(self, other: Any) -> Comparison: ...
    @overload
    def __ge__(self, other: VarArray | ParamArray | ExprArray) -> ComparisonArray: ...
    @overload
    def __ge__(self, other: Any) -> Comparison: ...
    @overload
    def __eq__(self, other: VarArray | ParamArray | ExprArray) -> ComparisonArray: ...
    @overload
    def __eq__(self, other: Any) -> Comparison: ...
    def __truediv__(self, other: float) -> Expr: ...

class Comparison: ...
class Constraint: ...
class Objective: ...

class Model:
    def __init__(self, name: str = ...) -> None: ...
    @property
    def name(self) -> str: ...
    def var(
        self,
        name: str,
        *,
        lb: float = ...,
        ub: float = ...,
        kind: str = ...,
    ) -> Var: ...
    def param(self, name: str, value: float) -> Param: ...
    @overload
    def add(self, comparison: Comparison, *, name: str | None = ...) -> Constraint: ...
    @overload
    def add(self, comparison: ComparisonArray, *, name: str | None = ...) -> ConstraintArray: ...
    @overload
    def add(self, comparison: Any, *, name: str | None = ...) -> Any: ...
    def vars(
        self,
        name: str,
        shape: int | tuple[int, ...],
        *,
        lb: float = ...,
        ub: float = ...,
        kind: str = ...,
    ) -> VarArray: ...
    def params(self, name: str, values: Any) -> ParamArray: ...
    def add_linear_rows(
        self,
        indptr: Any,
        indices: Any,
        data: Any,
        *,
        variables: VarArray,
        lower: Any,
        upper: Any,
        name: str | None = ...,
    ) -> ConstraintArray: ...
    def minimize(self, expr: Expr | Var | float) -> Objective: ...
    def maximize(self, expr: Expr | Var | float) -> Objective: ...
    def update(self, **values: Any) -> None: ...

class Solution:
    @property
    def status(self) -> SolveStatus: ...
    @property
    def has_primal(self) -> bool: ...
    @property
    def is_optimal(self) -> bool: ...
    @property
    def objective(self) -> float | None: ...
    @property
    def backend(self) -> str: ...
    @property
    def revision(self) -> int: ...
    def value(self, var: Var) -> float: ...
    def values(self, var_array: VarArray) -> Any: ...
    def dual(self, constraint: Constraint) -> float: ...
    def duals(self, constraint_array: ConstraintArray) -> Any: ...
    def reduced_cost(self, var: Var) -> float: ...
    @property
    def best_bound(self) -> float | None: ...
    @property
    def relative_gap(self) -> float | None: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def is_current(self, model: Model) -> bool: ...

class Highs:
    def __init__(
        self,
        *,
        threads: int = ...,
        output: bool = ...,
        time_limit: float | None = ...,
        relative_gap: float | None = ...,
        absolute_gap: float | None = ...,
        random_seed: int | None = ...,
    ) -> None: ...
    def close(self) -> None: ...
    def solve(
        self,
        model: Model,
        *,
        time_limit: float | None = ...,
        relative_gap: float | None = ...,
        absolute_gap: float | None = ...,
        random_seed: int | None = ...,
        start: Solution | None = ...,
    ) -> Solution: ...
    def __enter__(self) -> Highs: ...
    def __exit__(self, *args: Any) -> bool: ...


class VarArray:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, index: Any) -> Any: ...
    def __add__(self, other: Any) -> ExprArray: ...
    def __sub__(self, other: Any) -> ExprArray: ...
    def __mul__(self, other: Any) -> ExprArray: ...
    def __truediv__(self, other: float) -> ExprArray: ...
    def __le__(self, other: Any) -> ComparisonArray: ...
    def __ge__(self, other: Any) -> ComparisonArray: ...
    def __eq__(self, other: Any) -> ComparisonArray: ...

class ParamArray:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, index: Any) -> Any: ...
    def __add__(self, other: Any) -> ExprArray: ...
    def __sub__(self, other: Any) -> ExprArray: ...
    def __mul__(self, other: Any) -> ExprArray: ...
    def __truediv__(self, other: float) -> ExprArray: ...
    def __le__(self, other: Any) -> ComparisonArray: ...
    def __ge__(self, other: Any) -> ComparisonArray: ...
    def __eq__(self, other: Any) -> ComparisonArray: ...

class ExprArray:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, index: Any) -> Any: ...
    def __add__(self, other: Any) -> ExprArray: ...
    def __sub__(self, other: Any) -> ExprArray: ...
    def __mul__(self, other: Any) -> ExprArray: ...
    def __truediv__(self, other: float) -> ExprArray: ...
    def __le__(self, other: Any) -> ComparisonArray: ...
    def __ge__(self, other: Any) -> ComparisonArray: ...
    def __eq__(self, other: Any) -> ComparisonArray: ...

class ComparisonArray:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, index: Any) -> Any: ...

class ConstraintArray:
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __getitem__(self, index: Any) -> Any: ...

def sum(array: Any) -> Any: ...
def dot(coefficients: Any, expressions: Any) -> Any: ...
